name: Deploy Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies for generating JWT
        run: npm install @octokit/auth-app

      - name: Generate GitHub App JWT
        id: generate_jwt
        run: |
          echo "${{ secrets.GITHUB_APP_PRIVATE_KEY }}" > private-key.pem
          jwt=$(npx @octokit/auth-app create-jwt --app-id ${{ secrets.GITHUB_APP_ID }} --private-key-file private-key.pem)
          echo "jwt=${jwt}" >> $GITHUB_ENV

      - name: Get installation access token
        id: get_installation_token
        run: |
          token=$(curl -X POST \
            -H "Authorization: Bearer ${{ env.jwt }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/app/installations/${{ secrets.GITHUB_APP_INSTALLATION_ID }}/access_tokens)
          echo "token=$(echo $token | jq -r .token)" >> $GITHUB_ENV

      - name: Bump version and push tag
        id: version
        run: |
          git config --global user.email "manishabheemanpally@gmail.com"
          git config --global user.name "manishabheemanpally"

          # Fetch tags from the remote repository
          git fetch --tags

          # Get the current version tag
          current_version=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
          echo "Current version: $current_version"

          # Calculate the new version tag
          new_version=$(echo $current_version | awk -F. -v OFS=. '{$NF++;print}')
          echo "New version: $new_version"

          # Check if the new version tag already exists in the remote repository
          if git rev-parse "refs/tags/$new_version" >/dev/null 2>&1; then
            echo "Tag $new_version already exists. Skipping tag creation."
            echo "new_version=" >> $GITHUB_ENV
          else
            git tag $new_version
            echo "new_version=$new_version" >> $GITHUB_ENV

      - name: Push new version tag
        if: env.new_version != ''
        env:
          GITHUB_TOKEN: ${{ env.token }}
        run: |
          git push https://x-access-token:${{ env.token }}@github.com/manishabheemanpally/pythontask.git ${{ env.new_version }}

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to another repository
        env:
          GITHUB_TOKEN: ${{ env.token }}
        run: |
          set -e  # Exit immediately if any command fails

          git config --global user.email "manishabheemanpally@gmail.com"
          git config --global user.name "manishabheemanpally"

          # Construct the remote URL
          REMOTE_URL="https://x-access-token:${{ env.token }}@github.com/manishabheemanpally/deployrepo.git"
          echo "Using remote URL: $REMOTE_URL"

          # Add the target repository as a remote
          echo "Setting up target repository remote"
          git remote add target_repo "$REMOTE_URL"
          git remote -v

          # Fetch from the target repository
          echo "Fetching from target repository"
          git fetch target_repo || { echo 'Fetch failed'; exit 1; }

          # Ensure the target branch exists
          if git show-ref --quiet refs/heads/mainbranch; then
            git checkout mainbranch
          else
            git checkout -b mainbranch
          fi

          # Merge changes from origin/main allowing unrelated histories
          echo "Merging changes from origin/main"
          git merge origin/main --allow-unrelated-histories --no-ff --no-edit || { echo 'Merge failed'; exit 1; }

          # Push changes to the target repository using the token for authentication
          echo "Pushing changes to target repository"
          git push "$REMOTE_URL" mainbranch --force || { echo 'Push failed'; exit 1; }
