name: Deploy Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.email "manishabheemanpally@gmail.com"
          git config --global user.name "manishabheemanpally"

      - name: Deploy to another repository
        env:
          GH_PAT: ${{ secrets.MY_SECRET_KEYS }}
        run: |
          set -e
          
          # Cleanly construct the remote repository URL
          REMOTE_URL="https://x-access-token:${{ secrets.MY_SECRET_KEYS }}@github.com/manishabheemanpally/deployrepo.git"
          echo "Using remote URL: $REMOTE_URL"
          
          # Set up the remote repository
          echo "Setting up target repository remote"
          git remote add target_repo "$REMOTE_URL"
          git remote -v
          
          # Fetch from the target repository
          echo "Fetching from target repository"
          git fetch target_repo

          # Check if the branch exists in the target repository
          if git ls-remote --heads target_repo mainbranch | grep -q "refs/heads/mainbranch"; then
            echo "Checking out existing branch mainbranch"
            git checkout mainbranch
          else
            echo "Creating new branch mainbranch"
            git checkout -b mainbranch
          fi

          # Merge changes from origin/main
          echo "Merging changes from origin/main"
          if ! git merge origin/main --no-ff --no-edit; then
            echo "Merge conflict detected. Attempting to resolve..."
            
            # Attempt automatic conflict resolution
            git merge --strategy-option=theirs || {
              echo "Automatic conflict resolution failed. Aborting merge."
              git merge --abort
              exit 1
            }

            echo "Conflicts resolved. Proceeding with commit."
            git add .
            git commit -m "Resolved merge conflicts from origin/main"
          fi

          # Push changes to the target repository
          echo "Pushing changes to target repository"
          git push target_repo mainbranch



